export const tags = [
  {value: 'array', label: 'Array', selected: false},
  {value: 'hash-table', label: 'Hash Table', selected: false},
  {value: 'linked-list', label: 'Linked List', selected: false},
  {value: 'math', label: 'Math', selected: false},
  {value: 'recursion', label: 'Recursion', selected: false},
  {value: 'string', label: 'String', selected: false},
  {value: 'sliding-window', label: 'Sliding Window', selected: false},
  {value: 'binary-search', label: 'Binary Search', selected: false},
  {value: 'divide-and-conquer', label: 'Divide and Conquer', selected: false},
  {value: 'two-pointers', label: 'Two Pointers', selected: false},
  {value: 'dynamic-programming', label: 'Dynamic Programming', selected: false},
  {value: 'greedy', label: 'Greedy', selected: false},
  {value: 'trie', label: 'Trie', selected: false},
  {value: 'sorting', label: 'Sorting', selected: false},
  {value: 'backtracking', label: 'Backtracking', selected: false},
  {value: 'stack', label: 'Stack', selected: false},
  {value: 'heap-(priority-queue)', label: 'Heap (Priority Queue)', selected: false},
  {value: 'merge-sort', label: 'Merge Sort', selected: false},
  {value: 'string-matching', label: 'String Matching', selected: false},
  {value: 'bit-manipulation', label: 'Bit Manipulation', selected: false},
  {value: 'matrix', label: 'Matrix', selected: false},
  {value: 'monotonic-stack', label: 'Monotonic Stack', selected: false},
  {value: 'simulation', label: 'Simulation', selected: false},
  {value: 'combinatorics', label: 'Combinatorics', selected: false},
  {value: 'memoization', label: 'Memoization', selected: false},
  {value: 'tree', label: 'Tree', selected: false},
  {value: 'depth-first-search', label: 'Depth-First Search', selected: false},
  {value: 'binary-tree', label: 'Binary Tree', selected: false},
  {value: 'binary-search-tree', label: 'Binary Search Tree', selected: false},
  {value: 'breadth-first-search', label: 'Breadth-First Search', selected: false},
  {value: 'union-find', label: 'Union Find', selected: false},
  {value: 'graph', label: 'Graph', selected: false},
  {value: 'design', label: 'Design', selected: false},
  {value: 'doubly-linked-list', label: 'Doubly-Linked List', selected: false},
  {value: 'geometry', label: 'Geometry', selected: false},
  {value: 'interactive', label: 'Interactive', selected: false},
  {value: 'bucket-sort', label: 'Bucket Sort', selected: false},
  {value: 'radix-sort', label: 'Radix Sort', selected: false},
  {value: 'counting', label: 'Counting', selected: false},
  {value: 'data-stream', label: 'Data Stream', selected: false},
  {value: 'iterator', label: 'Iterator', selected: false},
  {value: 'database', label: 'Database', selected: false},
  {value: 'rolling-hash', label: 'Rolling Hash', selected: false},
  {value: 'hash-function', label: 'Hash Function', selected: false},
  {value: 'shell', label: 'Shell', selected: false},
  {value: 'enumeration', label: 'Enumeration', selected: false},
  {value: 'number-theory', label: 'Number Theory', selected: false},
  {value: 'topological-sort', label: 'Topological Sort', selected: false},
  {value: 'prefix-sum', label: 'Prefix Sum', selected: false},
  {value: 'quickselect', label: 'Quickselect', selected: false},
  {value: 'binary-indexed-tree', label: 'Binary Indexed Tree', selected: false},
  {value: 'segment-tree', label: 'Segment Tree', selected: false},
  {value: 'line-sweep', label: 'Line Sweep', selected: false},
  {value: 'ordered-set', label: 'Ordered Set', selected: false},
  {value: 'queue', label: 'Queue', selected: false},
  {value: 'monotonic-queue', label: 'Monotonic Queue', selected: false},
  {value: 'counting-sort', label: 'Counting Sort', selected: false},
  {value: 'brainteaser', label: 'Brainteaser', selected: false},
  {value: 'game-theory', label: 'Game Theory', selected: false},
  {value: 'eulerian-circuit', label: 'Eulerian Circuit', selected: false},
  {value: 'bitmask', label: 'Bitmask', selected: false},
  {value: 'randomized', label: 'Randomized', selected: false},
  {value: 'reservoir-sampling', label: 'Reservoir Sampling', selected: false},
  {value: 'shortest-path', label: 'Shortest Path', selected: false},
  {value: 'probability-and-statistics', label: 'Probability and Statistics', selected: false},
  {value: 'rejection-sampling', label: 'Rejection Sampling', selected: false},
  {value: 'suffix-array', label: 'Suffix Array', selected: false},
  {value: 'minimum-spanning-tree', label: 'Minimum Spanning Tree', selected: false},
  {value: 'concurrency', label: 'Concurrency', selected: false},
  {value: 'biconnected-component', label: 'Biconnected Component', selected: false},
  {value: 'strongly-connected-component', label: 'Strongly Connected Component', selected: false}
];
